### ISSUE TITLE
Can I disable or suppress PHP Fast Cache or does the framework require it?

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc-phpfastcache#3]
Hi @amostajo,

Sorry to bother you, I was trying to disable the cache by setting `'cache' => [ 'enabled' => false ]` in the Config/app.php.
However even with this set the plugin on install will create the cache folder. Changing or removing the `path` just means the folder is created in an alternate location.

So I guess my question is, can I disable phpfastcache or strip it somehow? I don't utilize it but wasn't sure if the framework required it for it's own needs.

Appreciated

**Comment by amostajo** [comment]
Disable it will make the cache not be in use, but it will create the folder structure.
